services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: neiro-calendar-frontend
    ports:
      - "3001:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - .env
    restart: unless-stopped